name: Build and release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '>=18'
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.19'
      - run: npm ci
      - run: npm run build
      - run: npm test
      - run: npm pack .
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            prebuilds/**/*
            dist/*
          if-no-files-found: error
          retention-days: 1

  test:
    needs: build
    strategy:
      matrix:
        target:
          - name: macos
            os: macos-latest
          - name: linux
            os: ubuntu-latest
          - name: windows
            os: windows-latest
    runs-on: ${{ matrix.target.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '>=18'
      - run: npm ci
      - uses: actions/download-artifact@v3
        with:
          name: build
      - run: npm test

  release:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '>=18'
      - run: npm ci
      - uses: actions/download-artifact@v3
        with:
          name: build
      - run: npm pack .
      - uses: actions/upload-artifact@v3
        with:
          name: release
          path: mysql-binlog-*.tgz
          if-no-files-found: error